CREATE SCHEMA `handytec-web` DEFAULT CHARACTER SET latin1 ;

use handytec-web;

CREATE TABLE `handytec-web`.`PARAMETER` (
  `CODE` VARCHAR(6) NOT NULL COMMENT '',
  `PARAMETER` VARCHAR(16) NOT NULL COMMENT '',
  `DESCRIPTION` VARCHAR(256) NOT NULL COMMENT '',
  PRIMARY KEY (`CODE`, `PARAMETER`)  COMMENT '');


  CREATE TABLE `handytec-web`.`CUSTOMER` (
  `ID` INT NOT NULL COMMENT '',
  `DATE` DATETIME NOT NULL COMMENT '',
  `NAME` VARCHAR(45) NOT NULL COMMENT '',
  `LAST_NAME` VARCHAR(45) NOT NULL COMMENT '',
  `EMAIL` VARCHAR(45) NOT NULL COMMENT '',
  `PHONE` VARCHAR(15) NOT NULL COMMENT '',
  `COMPANY` VARCHAR(45) NULL COMMENT '',
  `REQUIREMENT` VARCHAR(6) NOT NULL COMMENT '',
  `ORIGIN` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `CODE_idx` (`REQUIREMENT` ASC)  COMMENT '',
  INDEX `ORIGIN_idx` (`ORIGIN` ASC)  COMMENT '',
  CONSTRAINT `REQUIREMENT`
    FOREIGN KEY (`REQUIREMENT`)
    REFERENCES `handytec-web`.`PARAMETER` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORIGIN`
    FOREIGN KEY (`ORIGIN`)
    REFERENCES `handytec-web`.`PARAMETER` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;

ALTER TABLE `handytec-web`.`CUSTOMER` 
ADD COLUMN `SUSCRIBED` TINYINT NOT NULL DEFAULT 1 COMMENT '' AFTER `ORIGIN`;

ALTER TABLE `handytec-web`.`CUSTOMER` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '' ;

INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('WEB', 'REQUIREMENT', 'WEB SITE');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('MOB', 'REQUIREMENT', 'MOBILE APPLICATION');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('ITS', 'REQUIREMENT', 'INFORMATION TECHNOLOGY SERVICES');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('INF', 'REQUIREMENT', 'INFRAESTRUCTURE');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('TRA', 'REQUIREMENT', 'TRAINING');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('WRK', 'REQUIREMENT', 'WORK WITH US');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('OTH', 'REQUIREMENT', 'OTHER');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('WEB', 'ORIGIN', 'WEB BROWSER');
INSERT INTO `handytec-web`.`PARAMETER` (`CODE`, `PARAMETER`, `DESCRIPTION`) VALUES ('MOB', 'ORIGIN', 'MOBILE DEVICE');